name: Build

on:
  push:
    tags:
      - "v*"

jobs:
  x86_64-unknown-linux-musl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-musl
      - name: Setup artifacts
        run: |
          mkdir artifacts
          mv target/x86_64-unknown-linux-musl/release/mihoyo-api artifacts/mihoyo-api_x86_64-unknown-linux-musl
      - uses: actions/upload-artifact@v3
        with:
          name: x86_64-unknown-linux-musl
          path: artifacts/**
  x86_64-apple-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-apple-darwin
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-apple-darwin
      - name: Setup artifacts
        run: |
          mkdir artifacts
          mv target/x86_64-apple-darwin/release/mihoyo-api artifacts/mihoyo-api_x86_64-apple-darwin
      - uses: actions/upload-artifact@v3
        with:
          name: x86_64-apple-darwin
          path: artifacts/**
  x86_64-pc-windows-gnu:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-gnu
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-gnu
      - name: Setup artifacts
        run: |
          mkdir artifacts
          mv target/x86_64-pc-windows-gnu/release/mihoyo-api.exe artifacts/mihoyo-api_x86_64-pc-windows-gnu.exe
      - uses: actions/upload-artifact@v3
        with:
          name: x86_64-pc-windows-gnu
          path: artifacts/**
  Release:
    runs-on: ubuntu-latest
    needs:
      - x86_64-unknown-linux-musl
      - x86_64-apple-darwin
      - x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: x86_64-unknown-linux-musl
          path: artifacts
      - uses: actions/download-artifact@v3
        with:
          name: x86_64-apple-darwin
          path: artifacts
      - uses: actions/download-artifact@v3
        with:
          name: x86_64-pc-windows-gnu
          path: artifacts
      - uses: ncipollo/release-action@v1
        with:
          artifacts: artifacts/**
          token: ${{ secrets.GITHUB_TOKEN }}
